name: 'Download Prior Artifact'
description: 'Download an artifact from any prior workflow run of a given repository'
author: 'Alex Tompkins'
inputs:
  repo:
    required: true
    description: 'repository to search for artifacts'
    default: 'repo this action is running in'
runs:
  using: 'node16'
  main: 'dist/index.js'
